[workspace]
resolver = "2"
members = [
    "crates/grimoire-net",
    "crates/grimoire-pb",
    "crates/grimoire-common",
    "crates/grimoire-svcfw",
    "crates/grimoire-registry",
    "crates/grimoire-gateway",
    "crates/grimoire-room-svc",
    "crates/grimoire-battle-svc",
    "crates/grimoire-card-svc",
    "crates/grimoire-sim",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/differs/GRIMOIRE"

[workspace.dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "macros", "net", "io-util", "time", "sync", "signal"] }
prost = "0.13"
tonic = { version = "0.12", features = ["transport", "tls"] }
tonic-build = { version = "0.12", features = ["prost"] }
prost-build = "0.13"
protoc-bin-vendored = "3"
bytes = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
anyhow = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
futures = "0.3"
dashmap = "6"
rand = "0.8"
tokio-util = { version = "0.7", features = ["codec"] }
tokio-stream = "0.1"
clap = { version = "4", features = ["derive"] }
etcd-client = "0.13"
rustls = "0.23"
tokio-rustls = { version = "0.26", features = ["ring"] }
rustls-pemfile = "2"
kcp = "0.3"
sqlx = { version = "0.8", features = ["runtime-tokio", "postgres", "tls-none", "derive"] }
redis = { version = "0.27", features = ["tokio-comp"] }

[profile.release]
opt-level = 3
lto = "thin"
