[package]
name = "grimoire-svcfw"
version.workspace = true
edition.workspace = true

[dependencies]
grimoire-pb = { path = "../grimoire-pb" }
grimoire-net = { path = "../grimoire-net" }
grimoire-common = { path = "../grimoire-common" }
tokio.workspace = true
tokio-stream.workspace = true
tonic.workspace = true
bytes.workspace = true
tracing.workspace = true
anyhow.workspace = true
dashmap.workspace = true
sqlx.workspace = true
redis.workspace = true
serde.workspace = true
serde_json.workspace = true
